version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: waterways
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/waterways
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    container_name: grafana
  
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    container_name: loki

volumes:
  mysql_data: